ROTATING_MESSAGES = [
    "hi <@796444897238188052> big fan",
    "the person above me is suspicious",
    "sniper",
    "good morning",
    "howdy! :cowboy:",
    "hello robey100 server",
    "beep boop",
    "Hello! I am a bot created by robey100 and hary_.",
    "I can do many things, but right now I'm just here to say hi!",
    "I hope you're having a great day!",
    "are you a robot? yes, I am a robot! :robot:",
    "beep boop beep boop",
    "yo is this thing on? testing, testing, 1, 2, 3...",
    "can you hear me? I hope so! :ear:",
    "mmm, I smell something... is it pizza? :pizza:",
    "00:00:00 - the time when I was born! :birthday:",
    "Zzz... just kidding, I don't sleep! :sleeping:",
    "keep calm and let the bot handle it! :sunglasses:",
    "oh no, I think I just spilled some virtual coffee on my circuits! :coffee:",
    "10/10 would bot again! :star:",
    "are you a fan of memes? I sure am! :joy:",
    "did someone say 'fun'? because I'm all about fun! :tada:",
    "aw man I wish I could join in on the fun, but I'm just a bot! :sob:",
    "sniper mode activated! :crossed_swords:",
    "did someone say 'sniper'? because I'm always ready to snipe! :crossed_swords:",
    "uh oh, I think I just got sniped! :scream:",
    "alright everyone, time to get serious... just kidding, let's keep it fun! :wink:",
    "help me.",
    "i gave a second chance to cupid",
]